//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbSinavNotu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbfirstSinavNotu2Entities : DbContext
    {
        public DbfirstSinavNotu2Entities()
            : base("name=DbfirstSinavNotu2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDERS> TBLDERS { get; set; }
        public virtual DbSet<TBLNOT> TBLNOT { get; set; }
        public virtual DbSet<TBLOGRENCI> TBLOGRENCI { get; set; }
    
        public virtual ObjectResult<NOTLAR_Result> NOTLAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NOTLAR_Result>("NOTLAR");
        }
    
        public virtual ObjectResult<NOTLİSTESİ_Result> NOTLİSTESİ()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NOTLİSTESİ_Result>("NOTLİSTESİ");
        }
    }
}
